runtime: nodejs18
env: standard

handlers:
- url: /.*
  static_files: dist/index.html
  upload: dist/.*
  secure: always

- url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))
  static_files: dist/\1
  upload: dist/.*
  secure: always 